# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-05-06 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250)),
                ('nickname', models.CharField(max_length=250)),
                ('f_name', models.CharField(max_length=250)),
                ('l_name', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='receiver_msg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_msg_name', to='chatting.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_msg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_msg_name', to='chatting.User'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='receiver_inv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_inv_name', to='chatting.User'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='sender_inv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_inv_name', to='chatting.User'),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_name', to='chatting.User'),
        ),
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to='chatting.User'),
        ),
    ]
